dist: trusty
language: node_js
node_js:
  - lts/*
branches:
  only:
    - gh-pages
install:
  - npm install respec-validator
env:
  global:
    - URL="https://w3c.github.io/using-aria/ECHIDNA"
    - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
    - secure: "Pgu8TCvmxHer6IOsVhyUxldGuW852tW/khR/Yn+NNbx9uAIv2Az7C9t+OBaYjQksTkzqtItFX6W2gcgKtUSQq7L1q+dTHbaJydu76qKVcytlJPz+voSJ849QGe+qhyixEgVLmWohssF9A7K4WCdU1ZOpYN725DM2Rfh+x9pI0VU="

script:
  - npx respec-validator --no-links --gh-user=$GH_USER --gh-token=$GH_TOKEN index.html

after_success:
  - CC="mcaceres@mozilla.com,sohara@paciellogroup.com"
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN" --data "cc=$CC"
